---
# This playbook provisions a new Raspberry Pi
# as Ryan's home server.

- hosts: pi-lab
  remote_user: "{{ username }}"
  gather_facts: no
  tasks:
    - include: tasks/init.yml
      ignore_unreachable: yes
    - include: tasks/config.yml
    - include: tasks/docker.yml
  vars_files:
    - vars/vault.yml
  vars_prompt:
    - name: ansible_become_pass
      prompt: "Enter password for {{ username }}@{{ hostname }}"
      private: yes
