---
# This playbook provisions a new Raspberry Pi
# as Ryan's home server.

- hosts: pi-lab
  remote_user: "{{ username }}"
  gather_facts: no
  roles:
    - create_user_account
    - configure_system_resources
    - install_apt_packages
    - configure_network_services
    - configure_usb_storage
    - configure_scheduled_backups
    - populate_homedir
    - install_docker
    - launch_docker_services
  vars_files:
    - group_vars/pi-lab/vault
  vars_prompt:
    - name: ansible_become_pass
      prompt: "Enter password for {{ username }}@{{ hostname }}"
      private: yes
