---

- name: Installing base packages
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - git
      - stow
      - ufw
      - fail2ban
      - vim
