---

- name: Getting local IP
  delegate_to: localhost
  shell: "hostname -I | cut -d' ' -f1"
  register: local_ip
  changed_when: no

- name: Adding local machine to /etc/exports file
  become: yes
  lineinfile:
    path: /etc/exports
    regexp: "^/media/data	{{ local_ip.stdout }}\\(rw,sync,no_subtree_check\\)$"
    line: "/media/data	{{ local_ip.stdout }}(rw,sync,no_subtree_check)"
  notify: Restarting nfs
