---

- name: Creating ddclient config directory
  file:
    state: directory
    path: .local/etc/ddclient
- name: Copying ddclient.conf
  copy:
    dest: .local/etc/ddclient/ddclient.conf
    mode: 0644
    content: "{{ ddclient_config }}"
- name: Getting user uid
  command: "id -u {{ username }}"
  register: uid
  changed_when: no
- name: Getting user gid
  command: "id -g {{ username }}"
  register: gid
  changed_when: no
- name: Launching ddclient
  docker_service:
    project_name: ddclient
    definition:
      version: "2"
      services:
        ddclient:
          image: linuxserver/ddclient
          container_name: ddclient
          environment:
            PUID: "{{ uid.stdout }}"
            PGID: "{{ gid.stdout }}"
            TZ: "{{ timezone }}"
          volumes:
            - "/home/{{ username }}/.local/etc/ddclient:/config"
          restart: unless-stopped
