---

- name: Creating ryanlue.com nginx config directory
  file:
    state: directory
    path: .local/etc/nginx/blog.conf.d
- name: Creating ryanlue.com nginx config
  copy:
    dest: .local/etc/nginx/blog.conf.d/default.conf
    mode: 0644
    content: |
      server {
          listen       80;
          server_name  localhost;

          location / {
              root   /usr/share/nginx/html;
              index  index.html index.htm;

              # per https://sixtwothree.org/posts/nginx-configuration-removing-html-file-extensions-and-trailing-slashes
              rewrite ^(/.*)\.html(\?.*)?$ $1$2 permanent;
              rewrite ^/(.*)/$ /$1 permanent;

              try_files $uri/index.html $uri.html $uri/ $uri =404;
          }

          error_page   500 502 503 504  /50x.html;
          location = /50x.html {
              root   /usr/share/nginx/html;
          }
      }
- name: Cloning ryanlue.com repo
  git:
    repo: https://github.com/rlue/ryanlue.com.git
    dest: src/ryanlue.com
- name: Creating post-receive hook
  copy:
    dest: src/ryanlue.com/.git/hooks/post-receive
    mode: 0755
    content: |
      #!/bin/bash -l

      export PATH="$HOME/.rbenv/shims:$HOME/.rbenv/bin:$PATH"
      GIT_REPO="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && dirname "$(git rev-parse --git-dir)")"
      PUBLIC_WWW=$HOME/www/ryanlue.com

      cd $GIT_REPO
      bundle install
      bundle exec jekyll build --source $GIT_REPO --destination $PUBLIC_WWW
- name: Running post-receive hook
  shell: ./post-receive
  args:
    chdir: src/ryanlue.com/.git/hooks
    creates: ../../../../www/ryanlue.com

- name: Launching nginx-blog
  docker_service:
    project_name: nginx-blog
    definition:
      version: "2"
      services:
        nginx-blog:
          restart: always
          image: arm32v6/nginx:alpine
          container_name: nginx-blog
          networks:
            - nginxproxy_default
          volumes:
            - "/home/{{ username }}/www/ryanlue.com:/usr/share/nginx/html:ro"
            - "/home/{{ username }}/.local/etc/nginx/blog.conf.d:/etc/nginx/conf.d"
          environment:
            VIRTUAL_HOST: ryanlue.com,www.ryanlue.com
            LETSENCRYPT_HOST: ryanlue.com,www.ryanlue.com
            LETSENCRYPT_EMAIL: hello@ryanlue.com
      networks:
        nginxproxy_default:
          external: true
