---

- name: Installing ruby dependencies
  become: yes
  apt:
    name:
      - libssl-dev
      - libreadline-dev
      - libxslt1-dev     # system libraries for
      - libxml2-dev      # nokogiri

- name: Cloning rbenv repo
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: .rbenv

- name: Installing rbenv
  shell: src/configure && make -C src
  args:
    chdir: .rbenv
    creates: libexec/rbenv-realpath.dylib

- name: Creating rbenv plugins folder
  file:
    state: directory
    path: .rbenv/plugins

- name: Cloning rbenv-update
  git:
    repo: https://github.com/rkh/rbenv-update.git
    dest: .rbenv/plugins/rbenv-update

- name: Cloning ruby-build
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: .rbenv/plugins/ruby-build

- name: Determining latest ruby version
  shell: ".rbenv/bin/rbenv install --list | grep '^\\s*[[:digit:]]\\.[[:digit:]]\\.[[:digit:]]$' | tail -n1 | awk '{print $NF}'"
  register: latest_ruby_version
  changed_when: no

- name: Installing latest ruby version
  shell: ".rbenv/bin/rbenv install -s {{ latest_ruby_version.stdout }}"
  register: rbenv_install
  changed_when: rbenv_install.stderr != ""

- name: Setting global ruby version
  copy:
    dest: .rbenv/version
    mode: 0644
    content: |
      {{ latest_ruby_version.stdout }}

- name: Setting local ruby version
  copy:
    dest: .config/.ruby-version
    mode: 0644
    content: |
      {{ latest_ruby_version.stdout }}

- name: Updating rubygems
  shell: .rbenv/shims/gem update --system --force
  register: update_gem
  changed_when: update_gem.stdout != "Latest version already installed. Done."

- name: Updating bundler
  shell: .rbenv/shims/gem update bundler --force
  register: update_bundler
  changed_when: update_bundler.stdout != "Updating installed gems\nNothing to update"
