---

- name: Restarting avahi-daemon
  become: yes
  service:
    name: avahi-daemon
    state: restarted

- name: Reconfiguring Wi-Fi network interface
  command: wpa_cli -i wlan0 reconfigure

- name: Restarting sshd
  become: yes
  service:
    name: ssh
    state: restarted

- name: Restarting nfs
  become: yes
  service:
    name: nfs-kernel-server
    state: restarted
