---

- name: Validating credentials for default user (pi)
  remote_user: pi
  wait_for_connection: { timeout: 1 }
  ignore_errors: yes
  register: connection
  changed_when: not connection.changed
  notify: remove default user

- block:
  - name: "Validating credentials for new user ({{ username }})"
    wait_for_connection: { timeout: 1 }
  rescue:
    - name: "Creating user {{ username }}"
      remote_user: pi
      become: yes
      user:
        name: "{{ username }}"
        comment: "{{ realname }}"
        password: "{{ ansible_become_pass | password_hash('sha512', 'KKl.Qj3JIL5yVjlv') }}"
        groups: adm,dialout,cdrom,sudo,audio,video,plugdev,games,users,input,netdev,gpio,i2c,spi # see https://raspberrypi.stackexchange.com/a/75681
        shell: /bin/bash
        append: yes
    - name: Authorizing SSH key
      remote_user: pi
      become: yes
      authorized_key:
        user: "{{ username }}"
        key: "{{ ssh_key }}"
