---

- name: Getting default user's processes
  listen: remove default user
  shell: "ps -Upi -upi | grep -v grep | sed 1d | awk '{print $1}'"
  register: pi_processes
  changed_when: pi_processes.stdout != ""

- name: Waiting for default user's processes to die
  listen: remove default user
  wait_for:
    path: "/proc/{{ item }}/status"
    state: absent
  with_items: "{{ pi_processes.stdout_lines }}"

- name: Removing default user
  listen: remove default user
  become: yes
  user:
    name: pi
    state: absent
    remove: yes
