---

- name: "Registering variable: architecture"
  command: /usr/bin/dpkg --print-architecture
  register: architecture
  changed_when: False
- name: "Registering variable: dist_version"
  shell: /bin/grep ^VERSION= /etc/os-release | sed 's/^VERSION="[[:digit:]]\+ (\(.*\))"$/\1/'
  register: dist_version
  changed_when: False
- name: Adding Docker APT key
  become: yes
  apt_key:
    url: "https://download.docker.com/linux/raspbian/gpg"
    state: present
- name: Adding Docker APT repository
  become: yes
  apt_repository:
    repo: "deb [arch={{ architecture.stdout }}] https://download.docker.com/linux/raspbian {{ dist_version.stdout }} stable"
    state: present
- name: Installing Docker
  become: yes
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - docker-compose
      - python-docker
